from __future__ import annotations

import enum


class TransactionType(str, enum.Enum):
    UPI = "UPI"
    ATM = "ATM"
    CARD = "CARD"
    NEFT = "NEFT"
    RTGS = "RTGS"
    IMPS = "IMPS"
    LOAN_EMI = "LOAN_EMI"
    CREDIT_CARD = "CREDIT_CARD"
    OTHER = "OTHER"


class TransactionStatus(str, enum.Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING = "PENDING"
    REVERSED = "REVERSED"
    REFUNDED = "REFUNDED"


class DisputeCategory(str, enum.Enum):
    UPI_FAILED = "UPI_FAILED"
    UPI_PENDING = "UPI_PENDING"
    ATM_CASH_NOT_RECEIVED = "ATM_CASH_NOT_RECEIVED"
    UNAUTHORIZED_CARD_TRANSACTION = "UNAUTHORIZED_CARD_TRANSACTION"
    CARD_PAYMENT_FAILED = "CARD_PAYMENT_FAILED"
    REFUND_NOT_RECEIVED = "REFUND_NOT_RECEIVED"
    NEFT_RTGS_IMPS_ISSUE = "NEFT_RTGS_IMPS_ISSUE"
    WRONG_BANK_CHARGE = "WRONG_BANK_CHARGE"
    LOAN_EMI_DISPUTE = "LOAN_EMI_DISPUTE"
    CREDIT_CARD_BILLING_DISPUTE = "CREDIT_CARD_BILLING_DISPUTE"
    UNKNOWN = "UNKNOWN"


class DisputeStatus(str, enum.Enum):
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    AWAITING_INFO = "AWAITING_INFO"
    AUTO_RESOLVED = "AUTO_RESOLVED"
    ESCALATED = "ESCALATED"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class DisputePriority(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class EscalationStatus(str, enum.Enum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class EscalationReason(str, enum.Enum):
    HIGH_RISK = "HIGH_RISK"
    FRAUD_SUSPECTED = "FRAUD_SUSPECTED"
    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    LOW_CLASSIFICATION_CONFIDENCE = "LOW_CLASSIFICATION_CONFIDENCE"
    CUSTOMER_NOT_VERIFIED = "CUSTOMER_NOT_VERIFIED"
    TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
    RULE_NOT_ELIGIBLE = "RULE_NOT_ELIGIBLE"
    HIGH_VALUE_TRANSACTION = "HIGH_VALUE_TRANSACTION"
    REPEATED_DISPUTE = "REPEATED_DISPUTE"
    SYSTEM_ERROR = "SYSTEM_ERROR"


class RiskLevel(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class UserRole(str, enum.Enum):
    CUSTOMER = "CUSTOMER"
    SUPPORT_AGENT = "SUPPORT_AGENT"
    DISPUTE_MANAGER = "DISPUTE_MANAGER"
    ADMIN = "ADMIN"


class NotificationType(str, enum.Enum):
    EMAIL = "EMAIL"
    SMS = "SMS"
    IN_APP = "IN_APP"


class NotificationStatus(str, enum.Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"


class AccountStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    FROZEN = "FROZEN"
    CLOSED = "CLOSED"


class CardStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


class AuditEventType(str, enum.Enum):
    AUTHENTICATION = "AUTHENTICATION"
    CLASSIFICATION = "CLASSIFICATION"
    TRANSACTION_LOOKUP = "TRANSACTION_LOOKUP"
    POLICY_RETRIEVAL = "POLICY_RETRIEVAL"
    RULE_EVALUATION = "RULE_EVALUATION"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"
    RESOLUTION = "RESOLUTION"
    REFUND_REQUEST = "REFUND_REQUEST"
    ESCALATION = "ESCALATION"
    HUMAN_AGENT_ACTION = "HUMAN_AGENT_ACTION"
    NOTIFICATION = "NOTIFICATION"
    DISPUTE_CREATED = "DISPUTE_CREATED"
    DISPUTE_UPDATED = "DISPUTE_UPDATED"


class ActorType(str, enum.Enum):
    SYSTEM = "SYSTEM"
    CUSTOMER = "CUSTOMER"
    AGENT = "AGENT"
    LLM = "LLM"
    RULES_ENGINE = "RULES_ENGINE"
